### ISSUE TITLE
 CV for cox models

### ISSUE THREAD

**Issue by edlee123** [bbalasub1/glmnet_python#10]
Hello,
Thank you for putting this together.  I'm thinking about helping out for CV for cox model.  Would the structure be much like implementation of cv of logistic glmnet? Or is there any trickyness to be aware?

**Comment by hanfang** [comment]
Hi there, 

You could try to follow the current code structure to make a pull request. I think the critical thing to do is to benchmark the implementation. Make sure we can get expected results like the ones from the below:
https://github.com/bbalasub1/glmnet_python/blob/master/test/glmnet_examples.ipynb

We should be using the testing data from [here] https://web.stanford.edu/~hastie/glmnet/glmnet_alpha.html). If you are interested in making a pull request, feel free to let us know. I will be happy to do a code review later. Thanks.

Best,
Han
