### ISSUE TITLE
Error no 10000

### ISSUE THREAD

**Issue by Salamandre92** [bbalasub1/glmnet_python#11]
Hello

I am using glint for a project, and the fit function doesn't work :
`glm.fit(self.trainData,self.trainLabel, relative_penalties=penalties)`
self.trainData and self.trainLabel are pandas DataFrame, penalties is a array of zeros and ones.

The problem is that the error message is absolutely not helping : 

File "/Users/celsloaner/Project/SPUDS/code/predictor.py", line 271, in trainModel
    glm.fit(self.trainData,self.trainLabel, relative_penalties=penalties)
  File "/anaconda/envs/SPUDS/lib/python3.5/site-packages/glmnet/logistic.py", line 189, in fit
    self._fit(X, y, sample_weight, relative_penalties)
  File "/anaconda/envs/SPUDS/lib/python3.5/site-packages/glmnet/logistic.py", line 365, in _fit
    _check_glmnet_error_flag(self.jerr_)
  File "/anaconda/envs/SPUDS/lib/python3.5/site-packages/glmnet/util.py", line 140, in _check_glmnet_error_flag
    raise RuntimeError(msg.format(jerr))
**RuntimeError: glmnet error no. 10000**

What is the error no 10000 ?

Thank you

**Comment by bbalasub1** [comment]
Can you provide more info -- OS, sample data, python version etc so we
could attempt to reproduce your error?

**Comment by bbalasub1** [comment]
Also try following the basic example in the "vignette" (linked from the
front page of git) to see if everything has compiled right.

**Comment by Salamandre92** [comment]
I tried on iOS and Linux, both have the same issue. That code (that  didn't write) worked on another dataset, but the error doesn't allow me to understand what is the problem with this particular dataset.

I am using Python 3.5, here is a sample data

```
POLICE_DISTRICT	LICENSE_CODE	site_count	total_entries	txtdiff	alcohol_license	age_at_inspection	prev_star_115	prev_star_156	prev_star_186	prev_star_1005	prev_star_1064	prev_star_1067	prev_star_other	insp_prev_180	insp_prev_365	insp_prev_730	insp_prev_3650	Unstamped_180	Unstamped_365	Unstamped_730	Unstamped_3650	anyvio_180	anyvio_365	anyvio_730	anyvio_3650	doah_180	doah_365	doah_730	doah_3650	dens_abs_ab	dens_abs_abn	dens_abs_n	dens_dif_ab	dens_dif_abn	dens_dif_n	week	Unstamped
14	1781	1	3	0.548672641	1	4394	0	0	0	0	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.580669814	0.02263297	-0.140516649	1.399031678	0.591573913	0.280541296	14	0
```

**Comment by bbalasub1** [comment]
Hi

Would you pls send the data as an attachment to help troubleshoot? This
looks like only 1 row of the data. Thanks.

**Comment by Salamandre92** [comment]
Here it is

[tobaccoInspection_excel.xlsx](https://github.com/bbalasub1/glmnet_python/files/1005570/tobaccoInspection_excel.xlsx)

**Comment by Salamandre92** [comment]
Hello

I didn't receive any answer from you

**Comment by bbalasub1** [comment]
Sorry -- not enough information to troubleshoot this.
