### ISSUE TITLE
input type problem

### ISSUE THREAD

**Issue by kai0511** [bbalasub1/glmnet_python#15]
>   File "/exeh/exe3/zhaok/.local/lib/python3.5/site-packages/glmnet_python/glmnet.py", line 258, in g
> lmnet
>     raise ValueError('y input must be a scipy float64 ndarray')
> ValueError: y input must be a scipy float64 ndarray

After checking glmnet.py I found it has seriously type checking problem. I think scipy and numpy are actually the same thing, and I googled scipy.ndarray, and all results are about numpy.ndarray. So I think you should loose the condition and add isinstance(x, np.ndarray). 

And for classification I don't think y should be a type of float64.
Thanks for your time.

**Comment by kai0511** [comment]
I tested my modification on my fork of your repo. It works well on my machine.  More to https://github.com/kai0511/glmnet_python/blob/kai0511-patch-1/glmnet_python/glmnet.py

**Comment by bbalasub1** [comment]
These can be easily done outside the code rather than making numerous type checks/conversions with the functions. Makes life simpler to maintain and debug! Thanks.
