### ISSUE TITLE
Python 2.7 compatibility

### ISSUE THREAD

**Issue by staubda** [bbalasub1/glmnet_python#21]
Hey there, curious if you guys are interested in adding compatibility for Python 2 to this project. I've created a [fork](https://github.com/staubda/glmnet_python) making the (few) necessary changes. 

I've also done a bit of PEP8ing because I couldn't help myself. Happy to submit a PR if you're interested. You may need to run `pip install future --upgrade` to get it to work.

**Comment by bbalasub1** [comment]
That would be very helpful. I will take a look. Thanks.

**Comment by bbalasub1** [comment]
Since all of the testing was performed for 3.6, probably best if we keep it 3.6 compatible.
