### ISSUE TITLE
Minor problems with cvglmnetPlot.py and matplotlib3.0.0

### ISSUE THREAD

**Issue by michaelcoconnor** [bbalasub1/glmnet_python#35]
The matplotlib docs [here](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hold.html) and [here](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.html) confirm that `matplotlib.pyplot.hold` has been deprecated. Consequently with matplotlib3.0.0 cvglmnetPlot.py throws an error due to line 83: `plt.hold(True)`.

Also, `plt.show()` at the very end is commented out. These two glitches cause the `In [25]: cvglmnetPlot(cvmfit)` line in the tutorial [example](https://github.com/bbalasub1/glmnet_python/blob/master/test/glmnet_examples.ipynb) for the Linear Regression: Multiresponse Gaussian Family to fail.

**Comment by bbalasub1** [comment]
Many thanks! It has been removed now.
