### ISSUE TITLE
syntax error in glmnet function

### ISSUE THREAD

**Issue by nehamurad** [bbalasub1/glmnet_python#42]
```
import glmnet_python
from glmnet import glmnet
```

Gives the following error:

File "//anaconda2/lib/python2.7/site-packages/glmnet_python/glmnet.py", line 246
    def glmnet(*, x, y, family='gaussian', **options):
                ^
SyntaxError: invalid syntax

**Comment by bbalasub1** [comment]
Sorry -- difficult to troubleshoot without further info.

**Comment by nehamurad** [comment]
Hi if you pip install the latest glmnet there is a bug in it.

**Comment by bbalasub1** [comment]
OS?

**Comment by nehamurad** [comment]
macOS Mojave 10.14.6
