### ISSUE TITLE
which package to use?

### ISSUE THREAD

**Issue by StevenLi-DS** [bbalasub1/glmnet_python#43]
I'm a little bit confused with all the packages available via pip.

There is glment_python:
https://pypi.org/project/glmnet-python/#history

There is also glment_py:
https://pypi.org/project/glmnet-py/#history

but the description in glment_python says `pip install glmnet_py`.

**Comment by bbalasub1** [comment]
Yes. Please use glmnet_python. That is the most updated version.

**Comment by StevenLi-DS** [comment]
Thanks for the clarification. If I understand this correctly, currently `glment_py` cannot be run on Windows, right?

**Comment by bbalasub1** [comment]
I am not sure about the other version. Try this version though.

**Comment by chenz1hao** [comment]
> Thanks for the clarification. If I understand this correctly, currently `glment_py` cannot be run on Windows, right?

Can you run correctly on windows?
