### ISSUE TITLE
cvglmnet is throwing error about float to integer but glmnet is working fine

### ISSUE THREAD

**Issue by kputta** [bbalasub1/glmnet_python#44]
Warning: Non-fatal error in glmnet library call: error code =  -69
Check results for accuracy. Partial or no results returned.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-102-8434965c96f6> in <module>
      1 warnings.filterwarnings('ignore')
----> 2 cvfit = cvglmnet(x = X_train.head(10000).values, y = y_train.head(10000).values, ptype = 'mse', nfolds=10)
      3 warnings.filterwarnings('default')

~/miniconda3/envs/SANS37/lib/python3.7/site-packages/glmnet_python/cvglmnet.py in cvglmnet(x, y, family, ptype, nfolds, foldid, parallel, keep, grouped, **options)
    258 
    259     if len(foldid) == 0:
--> 260         ma = scipy.tile(scipy.arange(nfolds), [1, scipy.floor(nobs/nfolds)])
    261         mb = scipy.arange(scipy.mod(nobs, nfolds))
    262         mb = scipy.reshape(mb, [1, mb.size])

~/miniconda3/envs/SANS37/lib/python3.7/site-packages/numpy/lib/shape_base.py in tile(A, reps)
   1241                 c = c.reshape(-1, n).repeat(nrep, 0)
   1242             n //= dim_in
-> 1243     return c.reshape(shape_out)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

could be due to python3.7?

**Comment by bbalasub1** [comment]
Can you try switching the float64 to an int? Likely a numpy versioning
issue. Pls report back if that does not fix it.

**Comment by kputta** [comment]
it works

nfolds = 10
nobs = 100

doesn't work: scipy.tile((scipy.arange((nfolds))), [1, (scipy.floor(nobs/nfolds))])
works: scipy.tile((scipy.arange((nfolds))), [1, int(scipy.floor(nobs/nfolds))])

**Comment by bbalasub1** [comment]
For future reference:

I tried running the vignette with a fresh install using:

Python 3.6
Numpy 1.16.2
Gfortran/Gnu gcc 4.8.5

And it worked just fine.

**Comment by kputta** [comment]
Thanks

Best,
Kaushik
