### ISSUE TITLE
/lib/x86_64-linux-gnu/libgfortran.so.3: version `GFORTRAN_1.0' not found 

### ISSUE THREAD

**Issue by wasifmasood** [bbalasub1/glmnet_python#62]
Hi, 

I have install your package which initially relied on libgfortran.so.3. I had libgfortran.so.5 so I created a symbolic link to map libgfortran.so.3 to libgfortran.so.5 but now I am getting the following error:

`OSError: /lib/x86_64-linux-gnu/libgfortran.so.3: version `GFORTRAN_1.0' not found (required by /home/vagrant/miniconda3/envs/xai/lib/python3.9/site-packages/glmnet_python/GLMnet.so)`

Any recommendations please?

**Comment by bbalasub1** [comment]
Hi, I would recommend looking through previous threads to see if others have encountered similar issues. Secondly, it is very difficult for us to troubleshoot your particular problem from afar. There are too many idiosyncrasies associated with each machine and set up to get it fixed for everyone. So, you are on your own. 

I can only tell you that many folks have gotten this to work on a variety of OS. Best starting points to troubleshoot further are the threads.

Best wishes.
